services:
  db:
    build: .
    image: database-lab-project
    container_name: database-lab-project
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-21-database-lab-project}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    tmpfs:
      - /var/lib/postgresql/data