services:
  db:
    build: .
    image: database-lab-project
    container_name: database-lab-project
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    tmpfs:
      - /var/lib/postgresql/data