services:
  db:
    build: .
    image: database-lab-project
    container_name: database-lab-project
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 21-database-lab-project
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data