Enum "titolo_enum" {
  "Professore ordinario"
  "Professore associato"
  "Ricercatore"
}

Enum "periodo_enum" {
  "1"
  "2"
  "3"
}

Enum "giorno_enum" {
  "Lunedì"
  "Martedì"
  "Mercoledì"
  "Giovedì"
  "Venerdì"
}

Enum "fascia_oraria_enum" {
  "1"
  "2"
  "3"
  "4"
}

Table "dipartimento" {
  "codice" VARCHAR(10) [pk]
  "nome" VARCHAR(100) [not null]
}

Table "corso_di_laurea" {
  "codice" VARCHAR(10) [pk]
  "nome" VARCHAR(100) [not null]
}

Table "docente" {
  "cf" codice_fiscale [pk]
  "nome" VARCHAR(40) [not null]
  "cognome" VARCHAR(40) [not null]
  "titolo" titolo_enum [not null]
  "dipartimento" VARCHAR(10) [not null]
}

Table "studente" {
  "matricola" SERIAL [pk, increment]
  "nome" VARCHAR(40) [not null]
  "cognome" VARCHAR(40) [not null]
  "telefono" telefono_dom
  "aa_immatricolazione" anno_accademico [not null]
  "corso_di_laurea" VARCHAR(10) [not null]
}

Table "corso" {
  "codice" corso_dom [pk]
  "nome" VARCHAR(50) [not null]
  "crediti" INTEGER [not null]
  "descrizione" TEXT

  Checks {
    `crediti > 0` [name: 'ck_crediti']
  }
}

Table "edizione" {
  "codice_corso" corso_dom
  "anno_accademico" anno_accademico
  "periodo" periodo_enum

  Indexes {
    (codice_corso, anno_accademico, periodo) [pk]
    (codice_corso, anno_accademico) [unique, name: "uq_singola_edizione_annuale"]
  }
}

Table "lezione" {
  "codice_corso" corso_dom
  "anno_accademico" anno_accademico
  "periodo" periodo_enum
  "giorno" giorno_enum
  "fascia_oraria" fascia_oraria_enum
  "aula" VARCHAR(20) [not null]

  Indexes {
    (codice_corso, anno_accademico, periodo, giorno, fascia_oraria, aula) [pk]
    (anno_accademico, periodo, giorno, fascia_oraria, aula) [unique, name: "uq_occupazione_aula"]
  }
}

Table "esame" {
  "matricola" INTEGER
  "codice_corso" corso_dom
  "data_esame" DATE
  "punteggio" punteggio

  Checks {
    `data_esame <= CURRENT_DATE` [name: 'ck_data_esame']
  }

  Indexes {
    (matricola, codice_corso, data_esame) [pk]
  }
}

Table "piano_di_studio" {
  "matricola" INTEGER
  "codice_corso" corso_dom

  Indexes {
    (matricola, codice_corso) [pk]
  }
}

Table "prerequisito" {
  "codice_corso" corso_dom
  "codice_prerequisito" corso_dom

  Checks {
    `codice_corso <> codice_prerequisito` [name: 'ck_prerequisito']
  }

  Indexes {
    (codice_corso, codice_prerequisito) [pk]
  }
}

Table "abilitazione_docente_corso" {
  "cf_docente" codice_fiscale
  "codice_corso" corso_dom

  Indexes {
    (cf_docente, codice_corso) [pk]
  }
}

Table "insegnamento_edizione" {
  "cf_docente" codice_fiscale
  "codice_corso" corso_dom
  "anno_accademico" anno_accademico

  Indexes {
    (cf_docente, codice_corso, anno_accademico) [pk]
  }
}

Ref:"dipartimento"."codice" < "docente"."dipartimento" [update: cascade, delete: restrict]

Ref:"corso_di_laurea"."codice" < "studente"."corso_di_laurea" [update: cascade, delete: restrict]

Ref:"corso"."codice" < "edizione"."codice_corso" [update: cascade, delete: cascade]

Ref:"edizione".("codice_corso", "anno_accademico", "periodo") < "lezione".("codice_corso", "anno_accademico", "periodo") [update: cascade, delete: cascade]

Ref:"studente"."matricola" < "esame"."matricola" [update: cascade, delete: cascade]

Ref:"corso"."codice" < "esame"."codice_corso" [update: cascade, delete: restrict]

Ref:"studente"."matricola" < "piano_di_studio"."matricola"

Ref:"corso"."codice" < "piano_di_studio"."codice_corso"

Ref:"corso"."codice" < "prerequisito"."codice_corso"

Ref:"corso"."codice" < "prerequisito"."codice_prerequisito"

Ref:"docente"."cf" < "abilitazione_docente_corso"."cf_docente"

Ref:"corso"."codice" < "abilitazione_docente_corso"."codice_corso"

Ref:"docente"."cf" < "insegnamento_edizione"."cf_docente"

Ref:"edizione".("codice_corso", "anno_accademico") < "insegnamento_edizione".("codice_corso", "anno_accademico")
